### ISSUE TITLE
minor fixes to the albums table to be compatible with the spotify seed data

### ISSUE THREAD

**Issue by andreavanginneken** [Four-Butterflies/grace-shopper#10]

**Comment by burk96** [comment]
[80 albums](https://github.com/burk96/spotifyalbumcleaner/commit/d3ee70fcb1f178f08870f9dd751be66124b0ca97)

**Comment by burk96** [comment]
This will be complete when [this request](https://github.com/Four-Butterflies/grace-shopper/pull/14) is merged

**Comment by burk96** [comment]
complete
